default: &default
  adapter: postgresql
  encoding: unicode
  username: wale
  # password: 1234
  # password: admin
  password: Toyin@5315
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hotel_booking_app_backend

test:
  <<: *default
  database: hotel_booking_app_backend_test


production:
  <<: *default
  database: hotel_booking_app_backend_production
  username: hotel_booking_app_backend
  password: <%= ENV["HOTEL_BOOKING_APP_BACKEND_DATABASE_PASSWORD"] %>
